### ISSUE TITLE
rename input variables

### ISSUE THREAD

**Issue by Glenn-Terjesen** [entur/gha-helm#49]
Rename inputs:
https://github.com/entur/gha-helm/blob/8eca184dabb506d13726b191592b72babc596471/.github/workflows/deploy.yml#L35
https://github.com/entur/gha-helm/blob/main/.github/workflows/deploy.yml#L38

to gcp_project_id/ gcp_cluster_name (same as gha-meta+++)
Makes it clear that this is only for google cloud.

**Comment by AlexanderBrevig** [comment]
Though this is a breaking change, we should release it as a patch I think, since we are the only consumers of this feature as of now.
